### ISSUE TITLE
systemd config issues

### ISSUE THREAD

**Issue by kaso17** [chrisjohnson00/ansible-role-jackett#6]
Hi, this is kaso from the jackett team.
May I ask why you're starting jackett with MONO_TLS_PROVIDER=legacy + `--IgnoreSslErrors`? This shouldn't be needed.

For the latest pre release it's also mandatory to set the WorkingDirectory correctly.

If the integrated jackett update mechanism is supposed to work please also have a look at https://github.com/Jackett/Jackett/wiki/systemd-service 
If it's not supposed to be updated via jackett I'd recommend to add `--NoUpdates`

**Comment by chrisjohnson00** [comment]
The `--IgnoreSslErrors` is a parameter which is defaulted to `false` in the variable defaults.  It was part of a PR from another user.
I'll remove the TLS info, as i think that was a copy/paste from another Ansible Mono role.
I'll tag you in the PR for review, thanks!!
